In [8]:
import tensorflow as tf
import numpy as np

In [9]:
a=tf.constant(2)
b=tf.constant(3)
c=tf.constant(5)

In [10]:
add=tf.add(a,b)
subtract=tf.subtract(a,b)

In [11]:
print("Addition:", add.numpy())
print("Subtraction:", subtract.numpy())

Addition: 5
Subtraction: -1


In [12]:
mean=tf.reduce_mean([a,b,c])
print("Mean:", mean.numpy())

Mean: 3


In [16]:
matrix1=tf.constant([[1,2],[3,4]])
matrix2=tf.constant([[5,6],[7,8]])

In [18]:
product=tf.matmul(matrix1,matrix2)

In [19]:
product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [20]:
product.numpy()

array([[19, 22],
       [43, 50]])