In [3]:
import tensorflow as tf

In [4]:
from tensorflow import keras

In [7]:
from keras.preprocessing.sequence import pad_sequences #padding is used in NLP due to the mixed sizes of sentences
from keras.preprocessing.text import one_hot #one hot encoding
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding #this is for word embedding. 
from numpy import array

In [8]:
#defining docs

docs=['Hi, how are you doing?',
     'Hey,nice to see you.',
     'Hi,long time no see',
     'Hey, how was your day?',
     'Bye, I had a long day.',
     'Goodbye, I am leaving.',
     'Bye, take care.',
     'Bye Bye, see you tomorrow.']

In [12]:
vocab_size=10000 #A set of unique words in the text corpus is referred to as vocabulary

In [13]:
encoded_docs= [one_hot(d,vocab_size) for d in docs]

In [14]:
print(encoded_docs)

[[6846, 2720, 9702, 8042, 3406], [3935, 6155, 1546, 5460, 8042], [6846, 4691, 3743, 1527, 5460], [3935, 2720, 1115, 249, 289], [4598, 1765, 9762, 2183, 4691, 289], [6082, 1765, 7351, 8618], [4598, 5352, 4694], [4598, 4598, 5460, 8042, 8513]]


In [17]:
max_leng=8
padded_docs=pad_sequences(encoded_docs,maxlen=max_leng,padding='post') #padding can be done 'pre' or 'post'

In [18]:
print(padded_docs)

[[6846 2720 9702 8042 3406    0    0    0]
 [3935 6155 1546 5460 8042    0    0    0]
 [6846 4691 3743 1527 5460    0    0    0]
 [3935 2720 1115  249  289    0    0    0]
 [4598 1765 9762 2183 4691  289    0    0]
 [6082 1765 7351 8618    0    0    0    0]
 [4598 5352 4694    0    0    0    0    0]
 [4598 4598 5460 8042 8513    0    0    0]]


In [20]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_leng))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 8)              80000     
_________________________________________________________________
flatten (Flatten)            (None, 64)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 65        
Total params: 80,065
Trainable params: 80,065
Non-trainable params: 0
_________________________________________________________________
None


In [21]:
print(model.predict(padded_docs))

[[0.4944323 ]
 [0.4959454 ]
 [0.4851119 ]
 [0.50829816]
 [0.5011931 ]
 [0.48577785]
 [0.48820183]
 [0.5053238 ]]


In [24]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=max_leng))
model.compile('adam','mse')

In [25]:
print(model.predict(padded_docs))

[[[ 0.04537784  0.0083411   0.03081994 -0.0478183   0.04960659
   -0.01725149 -0.03183778  0.02988802 -0.00287731 -0.00790299]
  [ 0.01889605  0.02627499  0.02581621  0.02746418 -0.01059824
    0.04166779 -0.01684181  0.04155577  0.02775759  0.04204216]
  [-0.04900867 -0.0180701   0.0271724   0.03542208 -0.02660426
    0.0190523   0.03948892  0.0254466  -0.03122598 -0.00922215]
  [-0.034073    0.03794849 -0.00715496  0.01529953  0.03397324
   -0.01706555 -0.0359123   0.01282148  0.01515477 -0.02209485]
  [ 0.04826702  0.03211614  0.01470405 -0.03259025  0.00767369
    0.00182099 -0.01983203 -0.0235298   0.00010216 -0.04800428]
  [ 0.04085568 -0.03139321  0.01087933 -0.00090396  0.02564124
    0.0295238   0.03863974  0.01339442  0.01237983 -0.01873071]
  [ 0.04085568 -0.03139321  0.01087933 -0.00090396  0.02564124
    0.0295238   0.03863974  0.01339442  0.01237983 -0.01873071]
  [ 0.04085568 -0.03139321  0.01087933 -0.00090396  0.02564124
    0.0295238   0.03863974  0.01339442  0.012379